apiVersion: v1
kind: Namespace
metadata:
  name: medintel-prod
  labels:
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: medintel-monitoring
  labels:
    environment: production
