apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: medintel-prod
spec:
  provider: aws
  secretObjects:
    - secretName: medintel-db-secrets
      type: Opaque
      data:
        - objectName: rds_url
          key: DATABASE_URL
        - objectName: redis_url
          key: REDIS_URL
        - objectName: jwt_secret
          key: JWT_SECRET
  parameters:
    objects: |
      - objectName: "medintel/prod/db_url"
        objectType: "ssmparameter"
        objectAlias: "rds_url"
      - objectName: "medintel/prod/redis_url"
        objectType: "ssmparameter"
        objectAlias: "redis_url"
      - objectName: "medintel/prod/jwt_secret"
        objectType: "secretsmanager"
        objectAlias: "jwt_secret"
